TK_1_PPW/urls.py
from django.contrib import admin
from django.urls import path, include

# static files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls'), name='main'),
    path('approval-list/',include('approvalList.urls')),
    path('start-sell/',include('startsell.urls')),
    path('save-item/',include('sellItem.urls')),
    path('products/', include('products.urls'), name='products'),
    path('product-detail/', include('detailBarang.urls')),
    path('item-list/',include('itemList.urls'))
]

urlpatterns += staticfiles_urlpatterns()

sellItem/urls.py
from django.urls import path
from .views import saveItem

app_name = 'sellItem'

urlpatterns= [
	path('', saveItem, name = 'saveItem')
]

sellItem/models.py
from django.db import models

# Create your models here.
from decimal import Decimal

class Category(models.Model):
    name = models.TextField()
    price = models.DecimalField(max_digits=9, decimal_places=3, default=Decimal('0.0000'))

    DRESS = 'Dress'
    T_SHIRT = 'T-Shirt'
    SKIRT = 'Skirt'
    JUMPSUIT = 'Jumpsuit'
    PANTS_LEGGINGS = 'Pants & Leggings'
    JEANS = 'Jeans'
    SWIMWEAR = 'Swimwear'
    KNITWEAR_CARDIGANS = 'Knitwear & Cardigans'
    HOODIES_SWEATSHIRTS = 'Hoodies & Sweatshirts'
    BLAZER = 'Blazer'
    JACKET_COATS = 'Jacket & Coats'
    SLEEPWEAR = 'Sleepwear'
    ACCESSORIES = 'Accessories'
    ALL = 'All'

    CATEGORY_CHOICES = [
    (ALL, 'All'), (DRESS, 'Dress'), (T_SHIRT, 'T-Shirt'),
    (SKIRT, 'Skirt'), (JUMPSUIT, 'Jumpsuit'),
    (PANTS_LEGGINGS, 'Pants & Leggings'),
    (JEANS, 'Jeans'), (SWIMWEAR, 'Swimwear'),
    (KNITWEAR_CARDIGANS, 'Knitwear & Cardigans'),
    (HOODIES_SWEATSHIRTS, 'Hoodies & Sweatshirts'),
    (BLAZER, 'Blazer'), (JACKET_COATS, 'Jacket & Coats'),
    (SLEEPWEAR, 'Sleepwear'), (ACCESSORIES, 'Accessories')
    ]

    category = models.CharField(max_length = 100,
        choices=CATEGORY_CHOICES, default = ALL,
        )

    description = models.TextField()

sellItem/views.py
from django.shortcuts import render,redirect
from .form import addItem
from .models import Category

# Create your views here.
def saveItem(request):
	if request.method == 'POST':
		form = addItem(request.POST)
		if form.is_valid():
			Category.objects.create(**form.cleaned_data)
		form = addItem()
		categorys = Category.objects.all()
		context ={
			'form' : form,
			'category' : categorys
		}
		return render(request, 'sellItem/sellitem.html', context)
	else:
		form = addItem()
		categorys = Category.objects.all()
		context ={
			'form' : form,
			'category' : categorys
		}
	return render(request, 'sellItem/sellitem.html', context )

sellItem/templates/sellItem/sellitem.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel='stylesheet' href="{% static 'css/font-awsome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'top-footer.css' %}">
    <link rel="stylesheet" href="{% static 'bottom-footer.css' %}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Asap&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">

 
    <title>AppaRental</title>
</head>

<body>
    {% include 'top-footer.html' %}

    <div class="container-fluid" id="wrapper-top">
        <a class="tulisan-back" href="/products">
            <i class="fa fa-arrow-circle-left"></i>
            <p>Back to Products Page</p>
        </a>

        <div class="container-fluid" id="wrapper">
                
                <div class="bawah">
                    <h5>Sell Your Item</h5>
                    <hr>

                    <div class="container-fluid" id="wrapper_content">
                       <form method = "POST" action="{%url 'sellItem:saveItem' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class='bawah'>
                            <input type="submit" class="submit" value="Sell Item">
                        </div>
                    </div>

                </div>
        </div>
    </div>

    {% include 'bottom-footer.html' %}


    <!-- Optional JavaScript -->
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="{% static 'js/scrolling-nav.js' %}"></script>

</body>

</html>